# Use root/example as user/password credentials

services:
  
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=http://localhost:15000
    ports:
      - "3000:3000"