# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data/db
  
  todo-backend:
    image: todo-backend
    container_name: todo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    ports:
      - "15000:15000"
    depends_on:
      - mongo

  todo-frontend:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=http://localhost:15000
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
