# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://192.168.61.37:27017/todos
    ports:
      - "15000:15000"