name: Docker Image CI

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: 🚨 Checkout Repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Build Images
              run: |
                docker compose build
                docker images
            
            - name: Tag & push Backend
              run: |
                docker tag todo-backend:latest ${{ secrets.DOCKER_USER }}/todo-backend:latest
                docker push ${{ secrets.DOCKER_USER }}/todo-backend:latest

            - name: Tag & push Frontend
              run: |
                docker tag todo-frontend:latest ${{ secrets.DOCKER_USER }}/todo-frontend:latest
                docker push ${{ secrets.DOCKER_USER }}/todo-frontend:latest